// spec: gate-sdk/SPEC.md §check-graph — the coupling-graph projection: one node per `couples=`
// surface, one edge per registry member, grouped into the consumer's declared layers.
// `native/src/gates/graph.rs` reaches it in process rather than spawning it.
use crate::registry;
use crate::walk;
use std::collections::BTreeMap;

// spec: gate-sdk/SPEC.md §check-graph — the kit's default stylesheet, emitted when the consumer's
// theme directory supplies no `theme.css`. Byte-verbatim what the retired `graph_theme_css_default`
// heredoc emitted, which is what keeps a themeless consumer's artifact unchanged across the port.
const DEFAULT_CSS: &str = r##"    :root { color-scheme: light dark; }
    body { margin: 0; font: 15px/1.5 system-ui, sans-serif;
           background: #fff; color: #1a1a1a; }
    header { padding: 1rem 1.5rem; border-bottom: 1px solid #ddd; }
    header h1 { margin: 0 0 .35rem; font-size: 1.25rem; }
    header p { margin: .25rem 0; max-width: 68rem; }
    .status { font-size: .85rem; opacity: .7; }
    main { padding: 1rem 1.5rem; }
    .legend { margin-bottom: .75rem; font-size: .9rem; }
    .legend .valve { display: inline-block; width: 22px; border-top: 3px solid #d97706; }
    .viewport { border: 1px solid #ddd; border-radius: 8px; padding: 16px;
                background: #fafafa; overflow: auto; height: 78vh; cursor: grab; }
    .viewport.grabbing { cursor: grabbing; }
    .viewport svg { transform-origin: 0 0; max-width: none; }
    .hint { margin: .5rem 0 0; font-size: .8rem; opacity: .6; }
    @media (prefers-color-scheme: dark) {
      body { background: #16181d; color: #e6e6e6; }
      header { border-color: #333; }
      .viewport { border-color: #333; background: #0f1115; }
    }
"##;

const COMMENT_HEAD: &str = r##"<!--
  The check-coupling graph: which content surfaces each gates.list gate binds
  together.

  GENERATED, DO NOT EDIT. Source of truth is the per-gate `# graph:` manifests;
"##;

const HEAD_TOP: &str = r##"  check-graph (assertion E) fails if this file drifts from them.

  Reading it: nodes are surfaces (grouped by layer when the consumer's
  graph-vocab.sh declares layers); an edge is a gate. A bidirectional edge is a
  coupling bijection; a self-loop is a gate that guards one surface's internal
  consistency. Amber edges are cycle valves (valve=PROPOSED) - couplings where a
  leading surface may run ahead via a queue-tracked PROPOSED marker.

  Comment hygiene: arrows are named, never drawn, in this comment - an HTML
  comment-close sequence inside it would end the block and leak the rest.
-->
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Check-coupling graph</title>
  <style>
"##;

const HEAD_CHROME: &str = r##"  </style>
</head>
<body>
"##;

// spec: gate-sdk/SPEC.md §check-graph — the regen command the page names in its own prose, one
// spelling shared with the artifact's header comment below so a reader is never offered two.
const REGEN_CMD: &str = "bash gate-sdk/bin/run-gates.sh --emit graph";

const KIT_BODY_A: &str = r##"  <header>
    <h1>Check-coupling graph</h1>
    <p>Which content surfaces each <code>gates.list</code> gate binds together.
       Source of truth is the per-gate <code>graph:</code> manifests; this is
       their projection, regenerated by
       <code>"##;

const KIT_BODY_B: &str = r##"</code> and drift-checked
       by assertion E.</p>
    <p>Nodes are surfaces; an edge is a gate. A bidirectional edge is a coupling
       bijection; a self-loop guards one surface. Amber edges are cycle valves
       (<code>valve=PROPOSED</code>) - where a leading surface may run ahead via
       a queue-tracked marker.</p>
    <span class="status">Generated from the gate manifests - do not hand-edit.</span>
  </header>

  <main>
    <div class="legend">
      <span><span class="valve"></span> cycle valve (valve=PROPOSED)</span>
    </div>
    <div class="mermaid viewport" id="diagram"></div>
    <p class="hint">Ctrl/&#8984; + scroll to zoom &middot; drag to pan &middot; double-click to reset.</p>
  </main>

  <script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
    const dark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    const graph = `%%{init:{'theme':'${dark ? 'dark' : 'base'}','themeVariables':{'fontSize':'13px'}}}%%
"##;

// spec: gate-sdk/SPEC.md §check-graph — the emitted page's own script tail, held as an asset rather
// than as a string constant: it is a document the kit emits, not source this crate executes, and a
// Rust file carrying it would put the page's own `//` comments into the governed-comment corpus.
const TAIL: &str = include_str!("graph-tail.html");

const TAILEND: &str = r##"</body>
</html>
"##;

// spec: gate-sdk/SPEC.md §check-graph — one registry member's manifest, as the projection reads it
pub struct Member {
    pub name: String,
    pub couples: String,
    pub dir: String,
    pub valve: String,
}

// spec: gate-sdk/SPEC.md §check-graph — the resolved consumer config the projection and the gate
// share, so the two never resolve it twice and cannot disagree about it
pub struct Config {
    pub gates_dir: String,
    pub artifact: String,
    pub theme_dir: String,
    pub max_edges: String,
    pub layers: Vec<String>,
    pub layer_rules: Vec<String>,
    pub layer_default: String,
    pub kit_roots_rel: Vec<String>,
    pub resolve_dirs: Vec<String>,
}

impl Config {
    pub fn from_bridge() -> Result<Config, String> {
        let gates_dir = walk::knob_scalar("GATE_SDK_GATES_DIR")?;
        let resolve_dirs = registry::resolve_dirs(&gates_dir, &walk::kit_roots()?);
        Ok(Config {
            gates_dir,
            artifact: walk::knob_scalar("GATE_SDK_GRAPH_ARTIFACT")?,
            theme_dir: walk::knob_scalar("GATE_SDK_GRAPH_THEME_DIR")?,
            max_edges: walk::knob_scalar("GATE_SDK_GRAPH_MAX_EDGES")?,
            layers: walk::knob_array("GRAPH_LAYERS")?,
            layer_rules: walk::knob_array("GRAPH_LAYER_RULES")?,
            layer_default: walk::knob_scalar("GRAPH_LAYER_DEFAULT")?,
            kit_roots_rel: walk::knob_array("GATE_KIT_ROOTS_REL")?,
            resolve_dirs,
        })
    }

    pub fn list_path(&self) -> String {
        registry::list_path(&self.gates_dir)
    }
}

// spec: gate-sdk/SPEC.md §check-graph — the registry members the projection draws, deduplicated and
// byte-sorted. Byte order rather than the invoking locale's is a narrowing the port makes on
// purpose: under a non-C collation the shell's artifact was machine-dependent.
pub fn projected_members(cfg: &Config) -> Result<Vec<Member>, String> {
    let list = cfg.list_path();
    let text = std::fs::read_to_string(&list)
        .map_err(|e| format!("cannot read the registry at {}: {}", list, e))?;
    let mut names: Vec<String> = registry::members(&text);
    names.sort();
    names.dedup();

    let mut out: Vec<Member> = Vec::new();
    for name in names {
        let src = match registry::resolve(&name, &cfg.resolve_dirs) {
            Some(s) => s,
            None => continue,
        };
        let body = match std::fs::read_to_string(&src) {
            Ok(b) => b,
            Err(_) => continue,
        };
        let man = match registry::manifest_line(&body) {
            Some(m) => m,
            None => continue,
        };
        let f = registry::manifest_fields(man);
        out.push(Member {
            name,
            couples: registry::expand_couples(&registry::field(&f, "couples"), &cfg.kit_roots_rel),
            dir: registry::field(&f, "dir"),
            valve: registry::field(&f, "valve"),
        });
    }
    Ok(out)
}

// spec: gate-sdk/SPEC.md §check-graph — the retired `graph_surface_layer()` hook as data: an ordered
// `<path-prefix>:<layer-id>` roster split at the last `:`, first match wins, default otherwise.
// A prefix test rather than a glob, so this reader owns no glob semantics to disagree about.
pub fn surface_layer(surface: &str, cfg: &Config) -> String {
    for rule in &cfg.layer_rules {
        if let Some(at) = rule.rfind(':') {
            let (prefix, layer) = (&rule[..at], &rule[at + 1..]);
            if !prefix.is_empty() && surface.starts_with(prefix) {
                return layer.to_string();
            }
        }
    }
    cfg.layer_default.clone()
}

// spec: gate-sdk/SPEC.md §check-graph — layer_specs: the consumer's declared layers, or the single
// built-in bucket when it declares none
fn layer_specs(cfg: &Config) -> Vec<String> {
    if cfg.layers.is_empty() {
        vec!["surfaces:governed surfaces".to_string()]
    } else {
        cfg.layers.clone()
    }
}

// spec: gate-sdk/SPEC.md §check-graph — the mermaid flowchart body: subgraph declarations in
// declared-layer order, then one edge per member per coupled pair, then the cycle-valve link style
pub fn graph_text(cfg: &Config, members: &[Member]) -> String {
    let mut node_seen: BTreeMap<String, ()> = BTreeMap::new();
    for m in members {
        for s in m.couples.split(',') {
            node_seen.insert(s.to_string(), ());
        }
    }
    let nodes: Vec<String> = node_seen.keys().cloned().collect();
    let node_id: BTreeMap<&str, String> = nodes
        .iter()
        .enumerate()
        .map(|(i, n)| (n.as_str(), format!("n{}", i)))
        .collect();

    let mut edge_lines: Vec<String> = Vec::new();
    let mut proposed_idx: Vec<String> = Vec::new();
    let mut idx = 0usize;
    for m in members {
        if m.couples.is_empty() {
            continue;
        }
        let surf: Vec<&str> = m.couples.split(',').collect();
        let arrow = if m.dir == "bi" { "<-->" } else { "-->" };
        let src_id = &node_id[surf[0]];
        if surf.len() == 1 {
            edge_lines.push(format!("  {} {}|\"{}\"| {}", src_id, arrow, m.name, src_id));
            if m.valve == "PROPOSED" {
                proposed_idx.push(idx.to_string());
            }
            idx += 1;
        } else {
            for t in &surf[1..] {
                edge_lines.push(format!(
                    "  {} {}|\"{}\"| {}",
                    src_id, arrow, m.name, node_id[*t]
                ));
                if m.valve == "PROPOSED" {
                    proposed_idx.push(idx.to_string());
                }
                idx += 1;
            }
        }
    }

    let mut out = String::from("graph LR\n");
    for spec in layer_specs(cfg) {
        let (layer, label) = match spec.split_once(':') {
            Some((l, b)) => (l.to_string(), b.to_string()),
            None => (spec.clone(), spec.clone()),
        };
        let mut decl = String::new();
        for n in &nodes {
            if surface_layer(n, cfg) != layer {
                continue;
            }
            decl.push_str(&format!("    {}[\"{}\"]\n", node_id[n.as_str()], n));
        }
        if decl.is_empty() {
            continue;
        }
        out.push_str(&format!("  subgraph {}[\"{}\"]\n", layer, label));
        out.push_str(&decl);
        out.push_str("  end\n");
    }
    for e in &edge_lines {
        out.push_str(e);
        out.push('\n');
    }
    if !proposed_idx.is_empty() {
        out.push_str(&format!(
            "  linkStyle {} stroke:#d97706,stroke-width:2px;\n",
            proposed_idx.join(",")
        ));
    }
    // spec: gate-sdk/SPEC.md §check-graph — the shell form captured this in `$(…)`, which strips
    // every trailing newline, and printed it back with exactly one
    out.trim_end_matches('\n').to_string()
}

// spec: gate-sdk/SPEC.md §check-graph — one theme part, byte verbatim or absent. The kit adds and
// strips nothing, which is what makes a consumer's migration off the retired seam a move of the
// heredoc body rather than a re-authoring of it.
fn theme_part(theme_dir: &str, part: &str) -> Option<String> {
    std::fs::read_to_string(format!("{}/{}", theme_dir.trim_end_matches('/'), part)).ok()
}

// spec: gate-sdk/SPEC.md §check-graph — the projection itself. Callers: `--emit-graph` through
// run-gates' emit front-end, and `native/src/gates/graph.rs` in process.
pub fn render(cfg: &Config, members: &[Member]) -> String {
    let mut out = String::from("<!DOCTYPE html>\n");
    out.push_str(COMMENT_HEAD);
    out.push_str(&format!(
        "  regenerate with:  {} > {}\n",
        REGEN_CMD, cfg.artifact
    ));
    out.push_str(HEAD_TOP);
    out.push_str(&theme_part(&cfg.theme_dir, "theme.css").unwrap_or_else(|| DEFAULT_CSS.to_string()));
    out.push_str(HEAD_CHROME);
    if let Some(h) = theme_part(&cfg.theme_dir, "header.html") {
        out.push_str(&h);
    }
    out.push_str(KIT_BODY_A);
    out.push_str(REGEN_CMD);
    out.push_str(KIT_BODY_B);
    out.push_str(&graph_text(cfg, members));
    out.push('\n');
    out.push_str(&format!(
        "`;\n    mermaid.initialize({{ startOnLoad: false, maxEdges: {} }});\n",
        cfg.max_edges
    ));
    out.push_str(TAIL);
    if let Some(f) = theme_part(&cfg.theme_dir, "footer.html") {
        out.push_str(&f);
    }
    out.push_str(TAILEND);
    out
}

pub fn emit(_args: &[String]) -> Result<String, String> {
    let cfg = Config::from_bridge()?;
    let members = projected_members(&cfg)?;
    Ok(render(&cfg, &members))
}

#[cfg(test)]
mod tests {
    use super::*;

    // spec: gate-sdk/SPEC.md §check-graph — split at the LAST `:`, so a prefix carrying one resolves
    #[test]
    fn a_layer_rule_splits_at_its_last_colon_and_first_match_wins() {
        let cfg = Config {
            gates_dir: "scripts".into(),
            artifact: "a.html".into(),
            theme_dir: "scripts/graph-theme".into(),
            max_edges: "100".into(),
            layers: vec![],
            layer_rules: vec![
                "gate-sdk/:k_gate_sdk".into(),
                "gate-sdk/lib/:k_never_reached".into(),
                "odd:name/:k_odd".into(),
            ],
            layer_default: "k_shared".into(),
            kit_roots_rel: vec![],
            resolve_dirs: vec![],
        };
        assert_eq!(surface_layer("gate-sdk/lib/gate.sh", &cfg), "k_gate_sdk");
        assert_eq!(surface_layer("odd:name/x", &cfg), "k_odd");
        assert_eq!(surface_layer("README.md", &cfg), "k_shared");
    }
}
