// spec: docs/site-architecture.md §Generated projections and their freshness gates — the
// value-rollup block joins the enforcement map's per-kit class counts to the footprint's per-kit
// token cost. A consumer docs ruling, not kit mechanism: the join axis and column choice live here.
use crate::emit::enforcement_map;
use crate::emit::footprint;
use crate::marker;

const PAGE: &str = "docs/value.md";
const BEGIN: &str = "<!-- value-rollup:begin -->";
const END: &str = "<!-- value-rollup:end -->";

// spec: docs/site-architecture.md §Generated projections and their freshness gates — the join reads
// both emitters live rather than the committed detail pages, so a stale page cannot poison the
// rollup. It receives their *structured* values, so no rendered markdown is re-parsed.
struct Join {
    classes: Vec<String>,
    counts: Vec<(String, String)>,
    kits: Vec<String>,
    always: Vec<(String, String)>,
    triggered: Vec<(String, String)>,
    total_always: String,
    total_triggered: String,
}

// spec: context-kit/SPEC.md §bin/footprint — the rollup's cost columns are the token figure alone,
// the `~<n>t` the footprint cell carries; an absent tier stays an em dash
fn token_cell(lines: usize, bytes: usize) -> String {
    if lines == 0 && bytes == 0 {
        return "\u{2014}".to_string();
    }
    format!("~{}t", bytes / 4)
}

fn build() -> Result<Join, String> {
    let enf = enforcement_map::measure()?;
    let foot = footprint::measure()?;

    let classes: Vec<String> = enf.sections.iter().map(|s| s.title.clone()).collect();
    let mut counts: Vec<(String, String)> = Vec::new();
    for s in &enf.sections {
        for r in &s.rows {
            counts.push((format!("{}|{}", s.title, r.kit), String::new()));
        }
    }

    let kits: Vec<String> = foot.rows.iter().map(|r| r.kit.clone()).collect();
    let always: Vec<(String, String)> = foot
        .rows
        .iter()
        .map(|r| (r.kit.clone(), token_cell(r.always.lines, r.always.bytes)))
        .collect();
    let triggered: Vec<(String, String)> = foot
        .rows
        .iter()
        .map(|r| (r.kit.clone(), token_cell(r.triggered.lines, r.triggered.bytes)))
        .collect();

    Ok(Join {
        classes,
        counts,
        kits,
        always,
        triggered,
        total_always: token_cell(foot.always_total.lines, foot.always_total.bytes),
        total_triggered: token_cell(foot.triggered_total.lines, foot.triggered_total.bytes),
    })
}

fn count_of(j: &Join, class: &str, kit: &str) -> usize {
    let key = format!("{}|{}", class, kit);
    j.counts.iter().filter(|(k, _)| *k == key).count()
}

fn lookup(pairs: &[(String, String)], kit: &str) -> String {
    pairs
        .iter()
        .find(|(k, _)| k == kit)
        .map(|(_, v)| v.clone())
        .unwrap_or_else(|| "\u{2014}".to_string())
}

// spec: docs/site-architecture.md §Generated projections and their freshness gates — kit axis: the
// footprint roster first, in its order, then any enforcement-only label sorted
fn axis(j: &Join) -> Vec<String> {
    let mut out = j.kits.clone();
    let mut extra: Vec<String> = Vec::new();
    for (key, _) in &j.counts {
        let kit = key.split_once('|').map(|(_, k)| k).unwrap_or("");
        if !j.kits.iter().any(|k| k == kit) && !extra.iter().any(|k| k == kit) {
            extra.push(kit.to_string());
        }
    }
    extra.sort();
    out.extend(extra);
    out
}

fn body() -> Result<String, String> {
    let j = build()?;
    let mut out = String::from(
        "_Generated by `bash gate-sdk/bin/run-gates.sh --emit value-rollup --write`; do not hand-edit — `check-value-rollup-fresh` byte-compares this block against a fresh join._\n\n",
    );
    let mut hdr = String::from("| kit |");
    let mut sep = String::from("| --- |");
    for c in &j.classes {
        hdr.push_str(&format!(" {} |", c));
        sep.push_str(" --- |");
    }
    hdr.push_str(" always-loaded | load-triggered |");
    sep.push_str(" --- | --- |");
    out.push_str(&format!("{}\n{}\n", hdr, sep));

    let mut totals: Vec<usize> = vec![0; j.classes.len()];
    for kit in axis(&j) {
        let mut row = format!("| {} |", kit);
        for (i, c) in j.classes.iter().enumerate() {
            let n = count_of(&j, c, &kit);
            totals[i] += n;
            row.push_str(&if n == 0 {
                " \u{2014} |".to_string()
            } else {
                format!(" {} |", n)
            });
        }
        row.push_str(&format!(
            " {} | {} |",
            lookup(&j.always, &kit),
            lookup(&j.triggered, &kit)
        ));
        out.push_str(&format!("{}\n", row));
    }

    let mut trow = String::from("| **total** |");
    for t in &totals {
        trow.push_str(&format!(" {} |", t));
    }
    trow.push_str(&format!(" {} | {} |", j.total_always, j.total_triggered));
    out.push_str(&format!("{}\n", trow));
    // comment-tier-exempt: load-bearing blank — kramdown ends a GFM table only on a blank line,
    // else the :end marker abuts the last row and the block renders as a literal-pipe paragraph.
    out.push('\n');
    Ok(out)
}

// spec: gate-sdk/SPEC.md §The non-gate arm — `--write` rewrites the marker block in place through
// the shared marker writer, which refuses rather than appending on a missing pair; the bare arm
// prints the block body, the surface check-value-rollup-fresh byte-compares.
pub fn emit(args: &[String]) -> Result<String, String> {
    let text = body()?;
    if args.iter().any(|a| a == "--write") {
        marker::write_block(PAGE, BEGIN, END, &text)?;
        return Ok(format!("value-rollup: replaced the block in {}\n", PAGE));
    }
    Ok(text)
}
