#!/usr/bin/env bash
# spec: canon-kit/SPEC.md §The reference-link grammar — the on-site SPEC mirror rendered-doc references cite relatively; this emits it (check-docs-mirror-fresh gates staleness), preserving mirrored-page links and rewriting only source/directory links to the self-repo blob/tree grammar
# usage: gen-docs-mirror.sh [--write|--list|--emit <src>] [--root <dir>]
#   --write (default) writes every mirror page under <root>/docs/; --list prints the
#   source set; --emit prints one page. DOCS_MIRROR_BLOB_BASE overrides the base.
set -uo pipefail

SDK="${GATE_SDK_ROOT:-"${BASH_SOURCE[0]%/*}/../gate-sdk"}"
# shellcheck source=../gate-sdk/lib/gate.sh
source "$SDK/lib/gate.sh"

ROOT="."
MODE="write"
EMIT_SRC=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --write) MODE="write" ;;
        --list)  MODE="list" ;;
        --emit)  MODE="emit"; EMIT_SRC="${2:-}"; shift ;;
        --root)  ROOT="${2:-.}"; shift ;;
        *) echo "gen-docs-mirror: unknown argument: $1" >&2; exit 2 ;;
    esac
    shift
done
ROOT="${ROOT%/}"
[[ -d "$ROOT" ]] || { echo "gen-docs-mirror: not a directory: $ROOT" >&2; exit 2; }

BLOB_BASE="${DOCS_MIRROR_BLOB_BASE:-"$(gate_self_repo_prefix "${CANON_KIT_DOCS_BLOB_REF:-master}")"}"
TREE_BASE="${BLOB_BASE/\/blob\//\/tree\/}"

is_mirrored() {  # $1=repo-relative resolved path — a kit-level SPEC/README or the doctrine deliverable (the set this generator emits)
    case "$1" in
        */SPEC.md|*/README.md) [[ "$1" != */*/* ]] ;;   # exactly one dir segment
        doctrine-kit/DOCTRINE.md) return 0 ;;
        *) return 1 ;;
    esac
}

rewrite_target() {  # $1=srcdir (repo-relative dir of the source doc) $2=target — prints the (possibly unchanged) target
    local srcdir="$1" tgt="$2" path anchor res
    case "$tgt" in
        *"://"*|mailto:*|"#"*|*" "*) printf '%s' "$tgt"; return ;;  # external, anchor, or "title" suffix
    esac
    path="${tgt%%#*}"; anchor=""
    [[ "$tgt" == *#* ]] && anchor="#${tgt#*#}"
    [[ -z "$path" ]] && { printf '%s' "$tgt"; return ; }   # pure anchor
    res="$(realpath -m --relative-to="$ROOT" -- "$ROOT/$srcdir/$path" 2>/dev/null)"
    [[ -n "$res" ]] || { printf '%s' "$tgt"; return ; }
    if is_mirrored "$res" && [[ -f "$ROOT/$res" ]]; then
        printf '%s' "$tgt"                                  # topology-preserving: unchanged
    elif [[ -f "$ROOT/$res" ]]; then
        printf '%s%s%s' "$BLOB_BASE" "$res" "$anchor"       # source file -> blob
    elif [[ -d "$ROOT/$res" ]]; then
        printf '%s%s/' "$TREE_BASE" "$res"                  # directory -> tree
    else
        printf '%s' "$tgt"                                  # unresolved (e.g. fenced example): leave
    fi
}

emit_one() {  # $1=repo-relative source path (e.g. gate-sdk/SPEC.md)
    local src="$1" srcdir base title
    srcdir="${src%/*}"; base="${src##*/}"
    case "$base" in
        README.md)   title="README" ;;
        SPEC.md)     title="SPEC" ;;
        DOCTRINE.md) title="DOCTRINE" ;;
        *) echo "gen-docs-mirror: not a mirrored source: $src" >&2; return 2 ;;
    esac

    printf -- '---\n'
    printf 'title: %s\n' "$title"
    printf 'generated: true\n'
    printf -- '---\n'
    printf '<!-- Generated by scripts/gen-docs-mirror.sh from %s. Do not edit; run the generator. -->\n' "$src"

    # spec: canon-kit/SPEC.md §check-md-refs — a link target is the text between ]( and the next ), the shape check-md-refs and check-docs-link-convention key on
    local line out rest pre after tgt tail new
    while IFS= read -r line || [[ -n "$line" ]]; do
        out=""; rest="$line"
        while [[ "$rest" == *']('* ]]; do
            pre="${rest%%](*}"; after="${rest#*](}"
            if [[ "$after" == *')'* ]]; then
                tgt="${after%%)*}"; tail="${after#*)}"
                new="$(rewrite_target "$srcdir" "$tgt")"
                out+="${pre}](${new})"
                rest="$tail"
            else
                out+="${pre}](${after}"           # no closing ) — not a link, pass through
                rest=""
            fi
        done
        out+="$rest"
        printf '%s\n' "$out"
    done < "$ROOT/$src"
}

sources() {  # print every mirrored source path, repo-relative, sorted
    local d
    for d in "$ROOT"/*/; do
        d="${d#"$ROOT"/}"; d="${d%/}"
        [[ -f "$ROOT/$d/SPEC.md" ]] || continue
        printf '%s/SPEC.md\n' "$d"
        [[ -f "$ROOT/$d/README.md" ]] && printf '%s/README.md\n' "$d"
    done
    [[ -f "$ROOT/doctrine-kit/DOCTRINE.md" ]] && printf 'doctrine-kit/DOCTRINE.md\n'
}

if [[ "$MODE" == "list" ]]; then
    sources
    exit 0
fi

if [[ "$MODE" == "emit" ]]; then
    [[ -n "$EMIT_SRC" ]] || { echo "gen-docs-mirror: --emit needs a source path" >&2; exit 2; }
    [[ -f "$ROOT/$EMIT_SRC" ]] || { echo "gen-docs-mirror: source not found: $ROOT/$EMIT_SRC" >&2; exit 2; }
    emit_one "$EMIT_SRC"
    exit $?
fi

n=0
while IFS= read -r src; do
    dest="$ROOT/docs/$src"
    mkdir -p "${dest%/*}"
    emit_one "$src" > "$dest"
    n=$((n + 1))
done < <(sources)
echo "gen-docs-mirror: wrote $n mirror page(s) under $ROOT/docs/"
