#!/usr/bin/env bash
# spec: CLAUDE.md §Housekeeping — the value-rollup block in docs/value.md joins the enforcement-map's per-kit class counts to the footprint's per-kit token cost; a consumer docs ruling, not kit mechanism, so the join axis and column choice live here, never in a kit
# usage: gen-value-rollup.sh [--emit]
#   bare: rewrite the value-rollup marker block in docs/value.md in place (the env-probe marker precedent).
#   --emit: print the block body (the joined table) to stdout, the surface check-value-rollup-fresh byte-compares.
set -uo pipefail

SDK="${GATE_SDK_ROOT:-"${BASH_SOURCE[0]%/*}/../gate-sdk"}"
# shellcheck source=../gate-sdk/lib/inject.sh
source "$SDK/lib/inject.sh"

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT" 2>/dev/null || { echo "gen-value-rollup: cannot enter repo root" >&2; exit 2; }

PAGE="docs/value.md"
BEGIN="<!-- value-rollup:begin -->"
END="<!-- value-rollup:end -->"
ENFORCEMENT_EMITTER="gate-sdk/bin/enforcement-map.sh"
FOOTPRINT_EMITTER="context-kit/bin/footprint.sh"

emit=0
[[ "${1:-}" == "--emit" ]] && emit=1

# spec: CLAUDE.md §Housekeeping — the join reads the two emitters live (never the committed detail pages), so a stale committed page cannot poison the rollup; each page carries its own freshness gate
enf="$(bash "$ENFORCEMENT_EMITTER" --emit)"; est=$?
[[ "$est" -eq 0 ]] || { echo "gen-value-rollup: enforcement-map emitter failed (exit $est)" >&2; exit 2; }
foot="$(bash "$FOOTPRINT_EMITTER" --emit)"; fst=$?
[[ "$fst" -eq 0 ]] || { echo "gen-value-rollup: footprint emitter failed (exit $fst)" >&2; exit 2; }

# spec: CLAUDE.md §Housekeeping — the class taxonomy and its hardest-to-softest order are owned by the enforcement page; derive the columns from its `##` section headings rather than restating the class set here
declare -A CNT
declare -A KITSEEN
CLASSES=()
while IFS=$'\t' read -r tag col1 col2; do
    case "$tag" in
        CLASS) CLASSES+=("$col1") ;;
        COUNT) CNT["$col1|$col2"]=$(( ${CNT["$col1|$col2"]:-0} + 1 )); KITSEEN["$col2"]=1 ;;
    esac
done < <(awk '
    BEGIN { OFS = "\t" }
    /^## / { title = substr($0, 4); print "CLASS", title, ""; curclass = title; next }
    /^\|/ {
        if (curclass == "") next
        split($0, f, "|"); cell = f[2]; gsub(/^[ \t]+|[ \t]+$/, "", cell)
        if (cell == "kit" || cell == "---") next
        kit = cell
        if (match(cell, /^\[[^]]+\]/)) kit = substr(cell, 2, RLENGTH - 2)
        print "COUNT", curclass, kit
    }
' <<<"$enf")

# spec: CLAUDE.md §Housekeeping — the cost columns are the footprint's per-kit token figure; the `**total**` row carries the pre-summed token totals, so the rollup's totals row reuses them rather than re-summing token strings
declare -A FAL FTR
FKITS=()
TOT_AL="—"; TOT_TR="—"
while IFS=$'\t' read -r kit al tr; do
    if [[ "$kit" == '**total**' ]]; then
        TOT_AL="$al"; TOT_TR="$tr"
    else
        FKITS+=("$kit"); FAL["$kit"]="$al"; FTR["$kit"]="$tr"; KITSEEN["$kit"]=1
    fi
done < <(awk '
    BEGIN { OFS = "\t" }
    function tok(s) { gsub(/^[ \t]+|[ \t]+$/, "", s); if (match(s, /~[0-9]+t/)) return substr(s, RSTART, RLENGTH); return s }
    /^## Per-kit footprint/ { inpk = 1; next }
    /^## / { inpk = 0 }
    inpk && /^\|/ {
        split($0, f, "|"); kit = f[2]; gsub(/^[ \t]+|[ \t]+$/, "", kit)
        if (kit == "kit" || kit == "---") next
        print kit, tok(f[3]), tok(f[4])
    }
' <<<"$foot")

# spec: CLAUDE.md §Housekeeping — kit axis: the footprint kit roster first (its order), then any enforcement-only label (a surface under no kit groups as `(consumer)`), sorted
AXIS=("${FKITS[@]+"${FKITS[@]}"}")
extra=()
for k in "${!KITSEEN[@]}"; do
    [[ -n "${FAL[$k]+x}" ]] || extra+=("$k")
done
if [[ ${#extra[@]} -gt 0 ]]; then
    mapfile -t extra_sorted < <(printf '%s\n' "${extra[@]}" | sort)
    AXIS+=("${extra_sorted[@]}")
fi

hdr="| kit |"; sep="| --- |"
for c in "${CLASSES[@]+"${CLASSES[@]}"}"; do hdr+=" $c |"; sep+=" --- |"; done
hdr+=" always-loaded | load-triggered |"; sep+=" --- | --- |"

declare -A CTOTAL
rows=()
for kit in "${AXIS[@]+"${AXIS[@]}"}"; do
    row="| $kit |"
    for c in "${CLASSES[@]+"${CLASSES[@]}"}"; do
        n=${CNT["$c|$kit"]:-0}
        CTOTAL["$c"]=$(( ${CTOTAL["$c"]:-0} + n ))
        if [[ "$n" -eq 0 ]]; then row+=" — |"; else row+=" $n |"; fi
    done
    row+=" ${FAL[$kit]:-—} | ${FTR[$kit]:-—} |"
    rows+=("$row")
done

trow="| **total** |"
for c in "${CLASSES[@]+"${CLASSES[@]}"}"; do trow+=" ${CTOTAL[$c]:-0} |"; done
trow+=" $TOT_AL | $TOT_TR |"

emit_body() {
    printf '_Generated by `bash scripts/gen-value-rollup.sh`; do not hand-edit — `check-value-rollup-fresh` byte-compares this block against a fresh join._\n'
    printf '\n'
    printf '%s\n' "$hdr" "$sep"
    printf '%s\n' "${rows[@]}"
    printf '%s\n' "$trow"
    # comment-tier-exempt: load-bearing blank — kramdown ends a GFM table only on a
    # blank line, else the :end marker abuts the last row and the block renders as a
    # literal-pipe paragraph; command substitution strips it so the byte-compare holds.
    printf '\n'
}

if [[ "$emit" -eq 1 ]]; then
    emit_body
else
    action="$(emit_body | inject_marker_block "$PAGE" "$BEGIN" "$END")" \
        || { echo "gen-value-rollup: failed to write the value-rollup block into $PAGE" >&2; exit 2; }
    echo "gen-value-rollup: $action the value-rollup block in $PAGE"
fi
